Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,10 +13,12 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
-    - name: Extract ZIP
+    - name: Extract ZIP to root
       run: |
         unzip -o blackphoenixv2.zip -d .
         ls -la
+        echo "=== CHECK GRADLEW ==="
+        ls -la gradlew || echo "gradlew NOT FOUND!"
 
     - name: Setup Java 17
       uses: actions/setup-java@v4
@@ -33,7 +35,7 @@ jobs:
       run: chmod +x gradlew
 
     - name: Build APK
-      run: ./gradlew assembleDebug
+      run: ./gradlew assembleDebug --stacktrace
 
     - name: Upload APK
       uses: actions/upload-artifact@v4
